global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['flask-app:9100']
  - job_name: 'flask-app'
    static_configs:
      - targets: ['flask-app:5000']